name: GO_CI

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go get -v -t -d ./...
       
    - name: Build
      run: go build -o bin/golang-gin-poc -v .
  
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: execeute test
      run: go test service/*.go

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.5.7 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "fabioseba-video-app" #Must be unique in Heroku
          heroku_email: "sebastiano.fabio@gmail.com"